GET http://localhost:3000/Destinations

###

POST http://localhost:3000/InputLocation HTTP/1.1
content-type: application/json

{
    "name": "Brazil"
}

###

POST http://localhost:3000/SetDeleteLocation HTTP/1.1
content-type: application/json

{
    "RemoveLocation": "Brazil"
}

###

DELETE http://localhost:3000/DeleteCountry HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/GetCurrentLocation HTTP/1.1
content-type: application/json